// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CalculateY

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWBuffer<float3> Position;
#include "UnityCG.cginc"

[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!


    Position[id.x].y = sin(_Time.y + Position[id.x]);

}
